rootProject.name = "spring-security"
include("security-basic")
include("security-application")
include("security-filter")
include("security-csrf")
include("security-cors")
include("security-auth")
include("security-business")
include("security-oauth")
include("security-global-method")
include("security-method-filter")
include("security-repository-filter")
include("security-reactive")
include("security-test")
