POST http://localhost:8080/books
Content-Type: application/json
Authorization: Basic yong 12345

{
  "title": "The Lord of the Rings",
  "body": "test"
}

###

GET http://localhost:8080/books/1
Authorization: Basic yong 12345

###

GET http://localhost:8080/books/1
Authorization: Basic client 12345

###

GET http://localhost:8080/books
Authorization: Basic client 12345

###

GET http://localhost:8080/books/1
