POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "The Lord of the Rings",
  "body": "test"
}

###

GET http://localhost:8080/books/1


GET http://localhost:8080/books


###

GET http://localhost:8080/books/1
