GET http://localhost:8080/sell
Authorization: Basic readUser password

###

GET http://localhost:8080/sell
Authorization: Basic writeUser password

###

GET http://localhost:8080/find
Authorization: Basic readUser password

###

GET http://localhost:8080/find
Authorization: Basic writeUser password
