spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  docker:
    compose:
      file: ./security-dynamic-acl/docker-compose.yml