GET http://localhost:8080/hello

###

GET http://localhost:8080/hello
Authorization: Basic yong 12345

###
GET http://localhost:8080/hello
Authorization: Basic yo 12345


###
GET http://localhost:8080/ciao
Authorization: Basic yo 12345

###

GET http://localhost:8080/product/123
