version: '3'

services:
  security-db:
    image: mysql:8.0.30
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: security
    ports:
      - "3306:3306"
